### ISSUE TITLE
Invalid dependencies in environment.yml

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [VITA-Group/FSGS#6]
Invalid dependencies in `environment.yml`

In this commit https://github.com/VITA-Group/FSGS/commit/faa0bc57f1c14505791305dc1f3024a6dc680cab , @henrypearce4D added dependencies, which are not valid and do not appear in conda channels listed in `environment.yml`

As a result, it is not possible to run the code. The culprit packages are:

- `imageio=2.31.2`  (`imageio=2.31.4` exists though)
- `open3d=0.17.0`  ( in the channel `open3d-admin`, not listed in the yml, there is a `open3d=0.15.1` )
- `opencv_python=4.8.1.78` ( no trace of `opencv_python` anywhere. There are for example `opencv=4.6.0` in places but install fails with it)

It seems @henrypearce4D has access to some private channels unlisted here or something?

**Comment by henrypearce4D** [comment]
Ah sorry that's frustrating! I think I actually installed them via pip so that would explain it. I should have added them under pip in the environment.yml. 

I'll make a new PR, for now could you try this? 
(I'll leave out the versions just incase so it just installs the latest)

```
name: FSGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.8.1
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization-confidence
    - submodules/simple-knn
    - matplotlib
    - torchmetrics
    - timm
    - opencv_python
    - imageio
    - open3d
```

or if already installed 

`pip install matplotlib torchmetrics timm opencv_python imageio open3d`
